### PR TITLE
object files

### PR DESCRIPTION
**Pull request by DJNGattuso**
added some objects that i found for us to go through and potentially use in the project

### CODE REVIEW

**Comment by prince-chrismc** [comment]
branch name does not follow guidelines!

**Comment by DJNGattuso** [comment]
It's neither an exploration nor a feature....

**Comment by prince-chrismc** [comment]
than it could of been done directly on master

**Review by prince-chrismc — COMMENTED** [review]
I noticed many of these use directX texture files... which require a new library to use them

**Comment by DJNGattuso** [comment]
I tried on master but you have it blocked. It failed my push

**Comment by DJNGattuso** [comment]
But can't we add our textures to the objects?? I don't think it's specific to directX

**Comment by prince-chrismc** [comment]
well we will need an extra library to use them... I will check the project settings

**Review by prince-chrismc — CHANGES_REQUESTED** [review]
I think we should put them in a dropbox for now keeping only 1 or 2 'low poly' so we can begin working

**Comment by DJNGattuso** [comment]
i don't have space on my dropbox for the files. Let me see if i can put them elsewhere for now

**Comment by prince-chrismc** [comment]
I can do it it won't be a problem

**Comment by prince-chrismc** [comment]
https://www.dropbox.com/sh/abb584fhf104bcy/AAAP8MKp7TMl6TYjYGz96Uzza?dl=0

**Pull request closed without merging**
