### PR TITLE
texture class and adjustments

### PR DESCRIPTION
**Pull request by DJNGattuso**
NEED TO FIX THE LINK -> i attempted through defining stb_image_implementation as mentioned in learn OpenGL but it gives other link errors. 

we can also link it in the project properties but I don't want to change any settings...so maybe @prince-chrismc can do that.

But once thats done, we can run and test it. I attached a brick.jpg to the terrain and set it to repeat so it should cover the whole thing.

### CODE REVIEW

**Review by DanielPri — DISMISSED** [review]
rename your super long include to 
#include "stb_image.h"
Bunch of link errors need fixing

**Comment by DJNGattuso** [comment]
@DanielPri I get an error when i change the include to that. It doesn't work. We need to fix something to be able to use it that way

**Comment by prince-chrismc** [comment]
straight outta the .h ... you put it in the .h

> Do this:
      #define STB_IMAGE_IMPLEMENTATION
   before you include this file in *one* C or C++ file to create the implementation.
   // i.e. it should look like this:
   #include ...
   #include ...
   #include ...
   #define STB_IMAGE_IMPLEMENTATION
   #include "stb_image.h"

**Comment by prince-chrismc** [comment]
texture didnt work but keep going

**Comment by DJNGattuso** [comment]
yeah i can confirm that the issue is fixed with your latest commit and the texture isn't working. I'll look into it, must be a mapping

**Comment by prince-chrismc** [comment]
Closing this pull request due to the following:
1. more work has been agreed upon
2. The pull encompass more than initially planned

**Pull request closed without merging**
